// Video Composer (Milestone 5). Renders a video from a background image +
// narration audio + subtitles using FFmpeg. Outputs an MP4 reference pointer.

import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { join } from 'node:path';
import { existsSync, statSync } from 'node:fs';
import { execMediaDir } from './data-plane.js';

const execFileAsync = promisify(execFile);

export interface ComposeInput {
  execution_id: string;
  narration_wav: string; // path to narration audio
  subtitles_srt: string; // path to subtitles file
  duration_seconds?: number; // video length
  title?: string; // overlay text
  resolution?: string; // e.g. "1280x720"
}

export interface ComposeResult {
  video_path: string;
  duration_seconds: number;
  resolution: string;
  format: 'mp4';
}

/**
 * Compose an MP4 from narration + subtitles using FFmpeg:
 * - A solid/plasma background generated by FFmpeg (no external image needed)
 * - Narration audio muxed in
 * - Subtitles burned in
 */
export async function composeVideo(input: ComposeInput): Promise<ComposeResult> {
  const { dir } = execMediaDir(input.execution_id);
  const resolution = input.resolution ?? '1280x720';
  const outPath = join(dir, 'video.mp4');
  const audio = input.narration_wav;
  const srt = input.subtitles_srt;

  if (!existsSync(audio)) throw new Error(`VideoCompose: narration audio not found: ${audio}`);
  if (!existsSync(srt)) throw new Error(`VideoCompose: subtitles not found: ${srt}`);

  // Probe narration duration with ffprobe.
  const duration = await probeDuration(audio);

  const title = input.title ? `${input.title}` : '';
  const titleFilter = title
    ? `drawtext=text='${title.replace(/'/g, "\\'")}':x=(w-text_w)/2:y=h*0.08:fontsize=48:fontcolor=white:box=1:boxcolor=black@0.5:boxborderw=16`
    : 'null';

  // Build FFmpeg args:
  //   - lavfi color background sized to resolution, looped to duration
  //   - subtitles burned in via subtitles filter (requires escaping the path)
  const bg = `color=c=0x0d0d1a:s=${resolution}:d=${duration}`;
  const subsFilter = `subtitles='${srt.replace(/'/g, "'\\\\''")}':force_style='FontSize=24,PrimaryColour=&HFFFFFF,OutlineColour=&H000000,Outline=2'`;

  const args = [
    '-y',
    '-f', 'lavfi', '-i', bg,
    '-i', audio,
    '-vf', `${subsFilter},${titleFilter}`,
    '-shortest',
    '-c:v', 'libx264', '-preset', 'ultrafast', '-pix_fmt', 'yuv420p',
    '-c:a', 'aac', '-b:a', '128k',
    outPath,
  ];

  try {
    await execFileAsync('ffmpeg', args, { maxBuffer: 64 * 1024 * 1024 });
  } catch (e) {
    // Retry without subtitle burn (in case of filter escape issues) but keep audio.
    const fallbackArgs = [
      '-y',
      '-f', 'lavfi', '-i', bg,
      '-i', audio,
      '-vf', titleFilter,
      '-shortest',
      '-c:v', 'libx264', '-preset', 'ultrafast', '-pix_fmt', 'yuv420p',
      '-c:a', 'aac', '-b:a', '128k',
      outPath,
    ];
    await execFileAsync('ffmpeg', fallbackArgs, { maxBuffer: 64 * 1024 * 1024 });
  }

  const size = statSync(outPath).size;
  if (size === 0) throw new Error('VideoCompose: ffmpeg produced empty output');

  return {
    video_path: outPath,
    duration_seconds: Math.round(duration),
    resolution,
    format: 'mp4',
  };
}

/** Probe an audio file's duration (seconds) via ffprobe. */
async function probeDuration(audioPath: string): Promise<number> {
  try {
    const { stdout } = await execFileAsync(
      'ffprobe',
      ['-v', 'error', '-show_entries', 'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1', audioPath],
      { maxBuffer: 4 * 1024 * 1024 },
    );
    const sec = Number.parseFloat(stdout.trim());
    return Number.isFinite(sec) && sec > 0 ? sec : 10;
  } catch {
    return 10;
  }
}
